FROM adoptopenjdk/openjdk11:alpine-jre
COPY /home/ubuntu/public_content_to_aws/jars/dolphin-data-server-0.0.1-SNAPSHOT.jar /dolphin-data-server-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/dolphin-data-server-0.0.1-SNAPSHOT.jar"]
